### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:443 calling translate()

### ISSUE THREAD

**Issue by lucap84** [iamtraction/google-translate#24]
I'm using your library in straight way, very similar to the README but I receive a error trying to translate a simple text.

Installed with `npm install @iamtraction/google-translate`
this is my code:
```
const translate = require('@iamtraction/google-translate');

module.exports = {
    translateText: async () => {
        return await translate("translate this please", { from: 'en', to: 'it' });
    },
};
```

this is the result I obtain:
```
[2021-01-23T20:49:04.204Z] error RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (/Users/lpelosi/git/bghub-backend/node_modules/@iamtraction/google-translate/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/lpelosi/git/bghub-backend/node_modules/@iamtraction/google-translate/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```

Additional info:
npm version: `6.14.6`
node version: `v12.18.4`

Do you have any suggestion? Thanks!

**Comment by OMikiasO** [comment]
Any solutions?

**Comment by kakarot-dev** [comment]
It's something related to your local host
127.0.0.1 means your own computer

**Comment by CrackerakiUA** [comment]
@iamtraction any solutions for this?

**Comment by tranminhhuydn** [comment]
You try use this one


***@***.***/google-translate-api

Vào 20:50, Th 4, 2 thg 6, 2021 Honchar Denys ***@***.***> đã
viết:

**Comment by iamtraction** [comment]
try with the latest version of the library and see if you still have the issue. feel free to reopen the issue.
