### ISSUE TITLE
package doesnt work on heroku project

### ISSUE THREAD

**Issue by gco360** [iamtraction/google-translate#30]
hey i am having a discord bot and im using heroku-20 and node 14 and it seems that your project doesn't work i call it

**Comment by gco360** [comment]
please not the error i get is 
![Screenshot_4](https://user-images.githubusercontent.com/31587917/127777771-2e5bef87-d95b-46c9-9de5-9c15162d3753.png)

```
2021-08-01T16:06:54.588326+00:00 app[web.1]: SyntaxError: Unexpected end of JSON input
2021-08-01T16:06:54.588328+00:00 app[web.1]: at JSON.parse (<anonymous>)
2021-08-01T16:06:54.588331+00:00 app[web.1]: at translate (/app/node_modules/@iamtraction/google-translate/src/index.js:107:25)
2021-08-01T16:06:54.588332+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
