### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by losier** [iamtraction/google-translate#32]
hey i was trying to make a translate command for my discord bot but i'm facing HTTPSError i have a simple code like this
const arLang = await translate(Message, { to: 'ar' }); 
where Message is a message from a author and then it will send the translation to the discord channel and there is a catch block for err which gives HTTPError so IDK what should i do if you want i can provide you whole code too

note: 1st i thought i get this err cuz m trying to get 10 translation so i removed 9 of them but still the err was there

**Comment by iamtraction** [comment]
Can you send the entire error log?

**Comment by losier** [comment]
`/home/runner/Touka-Kirshima/node_modules/@iamtraction/google-translate/src/index.js:142
            let error = new Error();
                        ^

Error [HTTPError]
    at translate (/home/runner/Touka-Kirshima/node_modules/@iamtraction/google-translate/src/index.js:142:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async InteractionCollector.<anonymous> (/home/runner/Touka-Kirshima/SlashCommands/ContextMenu/translate.js:115:22) {
  statusCode: undefined,
  statusMessage: undefined`
}

**Comment by ElesGergo** [comment]
I am getting the same error as @losier. Any suggestions?

**Comment by Sagar409-conflict** [comment]
### **I am also getting same error.**

```
{ HTTPError
    at translate (/var/www/html/sawem/api/node_modules/@iamtraction/google-translate/src/index.js:142:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  statusCode: undefined,
  statusMessage: undefined }
```

**Comment by iamtraction** [comment]
Most likely a rate limit error. try with the latest version of the library. It'll show a more detailed error object.
